#!/bin/bash
#
# TITLE
#   tpfan
# DESCRIPTION
#   Control ThinkPad fan speed
#

current_speed=$( awk '/^level/{print $2}' /proc/acpi/ibm/fan )
new_speed="disengaged"

if [[ "x$1" != "x" ]]; then
    new_speed=$1
elif echo $current_speed | grep "disengaged" > /dev/null ; then
    new_speed=7
fi

echo level $new_speed | sudo tee /proc/acpi/ibm/fan
notify-send --icon=emblem-favorite "Fan Speed" "Was $current_speed now $new_speed"

