---

- hosts: all
  tasks:
    - group_by: key=user_{{ ansible_user_id }}

# First run, ansible user not yet created
- hosts: user_root
  gather_facts: no
  sudo: no
  roles:
    - install_ansible_pull

- hosts: '!user_root'
  gather_facts: no
  sudo: yes
  roles:
    # Included to maintain the ansible pull setup
    - install_ansible_pull
    - common

