---

# Install ansible in pull mode, from root account. Assumes virgin
# machine and defines ansible user, sudoers rules & crontab entry.

- hosts: install-pull-mode

  tasks:

    - name: Install ansible and deps
      yum: state=latest pkg=$item
      with_items:
        - git
        - ansible

    - name: Create ansible user
      user: state="present" name="ansible" system="yes" createhome="yes" generate_ssh_key="yes" comment="Ansible Configuration Management"

    - name: Add warning comment to ansible sudoers file
      lineinfile: state="present" dest="/etc/sudoers.d/ansible" create="yes" insertbefore="BOF" regexp="^(#|\s*)" line="## Automatically Managed by Ansible, Manual Changes Will Be Lost!"

    - name: Disable requiretty restriction on ansible user
      # NB: Full line in quotes due to : char, see ansible YAML disclaimer
      lineinfile: 'state="present" dest="/etc/sudoers.d/ansible" create="yes" regexp="^Defaults" line="Defaults: ansible !requiretty"'

    - name: Allow ansible user full sudo privs
      # NB: Full line in quotes due to : char, see ansible YAML disclaimer
      lineinfile: 'state="present" dest="/etc/sudoers.d/ansible" create="yes" regexp="^ansible" line="ansible ALL=(ALL) NOPASSWD: ALL"'

    - name: Install ansible pull-mode crontab entry
      cron: state="present" name="ansible-pull site.yml" user="ansible" special_time="hourly" job="ansible-pull -U https://github.com/CraigJPerry/home-network -d home-network -i hosts-production site.yml > /tmp/ansible-pull.$LOGNAME.crontab 2>&1"

    - name: Remove kickstart cronjob if present
      file: state=absent path="/etc/cron.d/ansible-pull-install"

