---

# Install ansible in pull mode.
#
# Designed to be run, unchanged:
#   * From a remote host, SSHing into an account with sudo privs
#   * From a remote host, SSHing into the root account
#   * Via the %post section of a kickstart automated install file
#   * Locally from the console as either root, or a user with sudo
#

- hosts: install-pull-mode
  tasks:
    - group_by: key=user_{{ ansible_user_id }}

- hosts: user_root
  gather_facts: no
  sudo: no
  roles:

    - bootstrap

- hosts: '!user_root'
  gather_facts: no
  sudo: yes
  roles:

    - bootstrap

