---

# Provision a vanilla VM with all requirements for running the
# playbook test cases under tests/ dir.

- hosts: vagrant
  sudo: yes

  roles:

    - ansible

  tasks:

    - name: Add host alias to hosts file
      lineinfile: state="present" dest="/etc/hosts" regexp="^127.0.0.1" line="127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4 vagrant-fedora-19"

