---

- include: playbooks/bootstrap.yml

- hosts: onsite
  sudo: yes
  gather_facts: no
  roles:
    - lan

- hosts: laptops
  sudo: yes
  gather_facts: no
  roles:
    - common
    - gnome
    - virtualisation
    - hardware
    - chrome
    - flash
    - dropbox
    - skype
    - steam

