---

- include: playbooks/bootstrap.yml

- hosts: all
  sudo: yes
  gather_facts: no
  roles:
    - users
    - common

- hosts: onsite:roaming
  sudo: yes
  gather_facts: no
  roles:
    - lan

- hosts: headed
  sudo: yes
  gather_facts: no
  roles:
    - hardware
    - desktop

- hosts: virtualisation-host
  sudo: yes
  gather_facts: no
  roles:
    - kvm
    - docker

