---

- include: playbooks/bootstrap.yml

- hosts: onsite
  sudo: yes
  gather_facts: no
  roles:
    - lan

- hosts: laptops:desktops
  sudo: yes
  gather_facts: no
  roles:
    - common
    - desktop
    - hardware
    - vagrant

- hosts: servers
  sudo: yes
  gather_facts: no
  roles:
    - kvm
    - docker

- hosts: virtual
  sudo: yes
  gather_facts: no
  roles:
    - common

