---

- include: playbooks/bootstrap.yml

- hosts: 'laptops:&user_root'
  sudo: no
  gather_facts: no
  roles:
    - common

- hosts: 'laptops:!user_root'
  sudo: yes
  gather_facts: no
  roles:
    - common

