---

- include: playbooks/bootstrap.yml

- hosts: onsite
  sudo: yes
  gather_facts: no
  roles:
    - lan

- hosts: laptops:desktops
  sudo: yes
  gather_facts: no
  roles:
    - common
    - desktop
    - virtualisation
    - hardware

- hosts: virtual
  sudo: yes
  gather_facts: no
  roles:
    - common

