---

- hosts: all
  connection: local

  tasks:

    - name: Configure network name services
      yum: pkg=$item state=latest
      sudo: yes
      with_items:
        - nss-mdns
        - avahi-tools

- include: desktops.yml

