---

# Sublime text editor

install_sublime: False
sublime_url: https://www.dropbox.com/s/0nvncgxcdwx5j40/
sublime_name: sublime_text_3_build_3059_x64.tar.bz2
sublime_unzipped: sublime_text_3

# Python

install_graphical_tools: False
install_pycharm: False
pycharm_url: http://download.jetbrains.com/python/
pycharm_name: pycharm-professional-4.0.6.tar.gz
pycharm_unzipped: pycharm-4.0.6
google_appengine_sdk_url: https://storage.googleapis.com/appengine-sdks/featured/
google_appengine_sdk_name: google_appengine_1.9.18.zip

# Java

jdk_download_root: http://download.oracle.com/otn-pub/java/jdk
jdk_version_dir: 8u31-b13
jdk_filename: jdk-8u31-linux-x64.rpm

install_idea: False
idea_url: http://download.jetbrains.com/python/
idea_url: http://download.jetbrains.com/idea/
idea_name: ideaIU-14.0.3.tar.gz
idea_unzipped: idea-IU-139.1117.1

