---

- hosts: pull-mode-hosts
  connection: local
  user: root

  tasks:

    - name: Create ansible user
      user: state="present" name="ansible" system="yes" createhome="yes" generate_ssh_key="yes" comment="Ansible Configuration Management"

