---

# Steam Gaming Platform & Game Tweaks / Fixes / Workarounds

- name: steam | Configure RPM Fusion repo
  copy: src=steam/etc/yum.repos.d/rpmfusion.repo
        dest=/etc/yum.repos.d/rpmfusion.repo
        owner=root group=root

- name: steam | Configure Fedora Steam repo
  copy: src=steam/etc/yum.repos.d/steam.repo
        dest=/etc/yum.repos.d/steam.repo
        owner=root group=root

- name: steam | Install
  yum: state=present enablerepo="rpmfusion-free,rpmfusion-free-updates,rpmfusion-nonfree,rpmfusion-nonfree-updates,steam" name="steam"

- name: steam | Install libGLU 32bit for Surgeon Simulator 2013
  yum: state=present name="mesa-libGLU.i686"

