---

# Steam Gaming Platform & Game Tweaks / Fixes / Workarounds

- name: Configure Fedora Steam repo
  copy: src=steam.repo dest=/etc/yum.repos.d/steam.repo owner=root group=root mode=0644

- name: Ensure Steam is not running
  shell: "/bin/ps -ef | /bin/grep /usr/bin/steam | /bin/grep -v grep"
  ignore_errors: yes
  changed_when: False
  register: steam_running

- name: Update Steam
  dnf: state=latest enablerepo="rpmfusion-free,rpmfusion-free-updates,rpmfusion-nonfree,rpmfusion-nonfree-updates,steam" name="steam"
  when: steam_running.rc != 0

- name: Install libGLU 32bit for Surgeon Simulator 2013
  dnf: state=present name="mesa-libGLU.i686"

