---

- name: Install Freenect
  yum: state=latest pkg={{ item }}
  with_items:
    - libfreenect-devel
    - libfreenect-opencv

- name: Install Kinect Python Binding Dependencies
  yum: state=latest pkg={{ item }}
  with_items:
    - libfreenect-python
    - opencv-python
    - Cython
    - numpy

- name: Configure udev rules
  copy: src=kinect/etc/udev/rules.d/66-kinect.rules
        dest=/etc/udev/rules.d/66-kinect.rules
        owner=root
        group=root

- name: Permit users access to device
  user: name={{ item }} append=yes groups=video
  with_items:
    - craig
    - dev

