---

- name: Unlock ThinkPad manual fan speed control
  lineinfile: state="present" dest="/etc/modprobe.d/thinkpad.conf" create="yes" insertbefore="BOF" regexp="^options" line="options thinkpad_acpi fan_control=1"

- name: Install tpfan helper
  copy: src=tpfan dest=/opt/bin/tpfan owner=root group=root mode=0755

