---

# Configure Citrix ICA Client

- name: Install ICAClient dependencies
  yum: state=present pkg={{ item }}
  with_items:
    - motif.i686
    - libXpm.i686
    - libXaw.i686

# Workaround: unarchive doesn't check if already unzipped in 1.4
- name: Check if ICAClient already unzipped
  command: find /usr/lib -maxdepth 1 -type d -name 'ICAClient'
  register: icaclient_unzipped
  changed_when: False

- name: Install ICAClient
  unarchive: src=ICAClient.tar.gz dest=/usr/lib
  when: icaclient_unzipped.stdout.find("ICAClient") == -1

- name: Define ICA mime type
  copy: src=ica.xml dest=/usr/share/mime/packages/ica.xml owner=root group=root mode=0644
  notify:
    - update gnome mime db
    - update xdg mime db

- name: Define ICA application
  copy: src=wfica.desktop dest=/usr/share/applications/wfica.desktop owner=root group=root mode=0644
  notify:
    - update gnome desktop db
    - update xdg desktop db

- name: Associate ICA mime type with handler
  lineinfile: 'state="present" dest="/usr/share/applications/defaults.list" insertafter="EOF" regexp="^application/x-ica=wfica.desktop" line="application/x-ica=wfica.desktop"'

