----

- name: Install Freenect Dependencies
  yum: pkg=$item state=latest
  with_items:
    - gcc-c++
    - libXi-devel
    - libXmu-devel
    - freeglut-devel
    - libusb-devel
    - libusbx-devel
  tags:
    - fedora_19

- name: Install Kinect Python Binding Dependencies
  yum: pkg=$item state=latest
  with_items:
    - Cython
    - numpy
    - opencv-python
  tags:
    - fedora_19 pythondev

- name: Clone Freenect Library Source
  git: repo=git://github.com/OpenKinect/libfreenect.git
       dest=/usr/local/src
  tags:
    - fedora_19

# TODO: As non root user!
- name: Create build directory
  file: path=/usr/local/src/libfreenect/build state=directory
  tags:
    - fedora_19

# TODO: As non root user!
- name: Configure libfreenect Source
  command: cmake -DBUILD_CV=ON -DBUILD_PYTHON=ON ..
           chdir=/usr/local/src/libfreenect/build
  tags:
    - fedora_19

# TODO: As non root user!
- name: Build libfreenect
  command: make
           chdir=/usr/local/src/libfreenect/build
  tags:
    - fedora_19

- name: Install libfreenect
  command: make install
           chdir=/usr/local/src/libfreenect/build
  tags:
    - fedora_19

- name: Configure ld cache
  copy: src=kinect/etc/ld.so.conf.d/libfreenect-x86_64.conf
        dest=/etc/ld.so.conf.d/libfreenect-x86_64.conf
        owner=root
        group=root
  tags:
    - fedora_19

- name: Configure udev rules
  copy: src=kinect/etc/udev/rules.d/66-kinect.rules
        dest=/etc/udev/rules.d/66-kinect.rules
        owner=root
        group=root
  tags:
    - fedora_19

# TODO: Ensure video group is present for udev rules & add kinect dev users to it

