---

- name: Install KVM & libvirt
  yum: state=latest pkg='@virtualization'

- name: Configure virtualbox repo
  copy: src=vagrant/etc/yum.repos.d/virtualbox.repo
        dest=/etc/yum.repos.d/virtualbox.repo
        owner=root group=root

- name: Install virtualbox
  yum: state=latest enablerepo="virtualbox" name="{{ virtualbox_package }}"

- name: Download virtualbox extensions
  get_url: url="{{ virtualbox_extensions_url }}{{ virtualbox_extensions_name }}" dest="/opt/{{ virtualbox_extensions_name }}" mode=0644
  register: vbe_downloaded

- name: Install virtualbox extensions
  shell: '/usr/bin/VBoxManage extpack install /opt/{{ virtualbox_extensions_name }}'
  when: vbe_downloaded|changed

- name: Add vboxusers
  user: name={{ item }} append=yes groups=vboxusers
  with_items: virtualbox_users

- name: Download Vagrant
  get_url: url="{{ vagrant_url }}{{ vagrant_name }}" dest="/opt/{{ vagrant_name }}" mode=0644

- name: Install Vagrant
  yum: state=present pkg={{ vagrant_name }}

