---

# Google chrome web browser

- name: Configure repo
  copy: src=chrome.repo
        dest=/etc/yum.repos.d/chrome.repo
        owner=root group=root

- name: Install Browser
  yum: state=present enablerepo="chrome" name="google-chrome-stable"

- name: Install Talk Plugin
  yum: state=present enablerepo="chrome" name="google-talkplugin"

