---

# Google chrome web browser

- name: Configure chrome repo
  copy: src=google-chrome.repo
        dest=/etc/yum.repos.d/google-chrome.repo
        owner=root group=root

- name: Configure google talk plugin repo
  copy: src=google-talkplugin.repo
        dest=/etc/yum.repos.d/google-talkplugin.repo
        owner=root group=root

- name: Install Browser
  yum: state=present enablerepo="chrome" name="google-chrome-stable"

- name: Install Talk Plugin
  yum: state=present enablerepo="chrome" name="google-talkplugin"

