---

- name: Configure virtualbox repo
  copy: src=virtualbox.repo
        dest=/etc/yum.repos.d/virtualbox.repo
        owner=root group=root

- name: Ensure Virtualbox is not running
  shell: "/bin/ps -ef | /bin/grep /usr/lib/virtualbox/VBoxSVC | /bin/grep -v grep"
  ignore_errors: yes
  changed_when: False
  register: virtualbox_running

- name: Update virtualbox
  dnf: state=latest enablerepo="virtualbox" name="{{ virtualbox_package }}"
  register: virtualbox_installed
  when: virtualbox_running.rc != 0

- name: Check virtualbox version
  shell: "/usr/bin/vboxmanage --version"
  register: virtualbox_version
  when: virtualbox_installed|changed

- name: Download virtualbox extensions
  get_url: url="http://download.virtualbox.org/virtualbox/{{ virtualbox_version.stdout.split("r")[0] }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout.split("r")[0] }}-{{ virtualbox_version.stdout.split("r")[1] }}.vbox-extpack" dest="/opt/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout.split("r")[0] }}-{{ virtualbox_version.stdout.split("r")[1] }}.vbox-extpack" mode=0644
  when: virtualbox_installed|changed

- name: Install virtualbox extensions
  shell: '/usr/bin/VBoxManage extpack install /opt/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout.split("r")[0] }}-{{ virtualbox_version.stdout.split("r")[1] }}.vbox-extpack'
  when: virtualbox_installed|changed

- name: Install virtualbox kernel driver
  shell: '/etc/init.d/vboxdrv setup'
  when: virtualbox_installed|changed

- name: Restart vbox driver service
  service: name=vboxdrv state=restarted enabled=yes
  when: virtualbox_installed|changed

- name: Maintain vboxusers
  user: name={{ item }} append=yes groups=vboxusers
  with_items: virtualbox_users

