---

# Network configuration for LAN

- name: Zeroconf (bonjour) network name services & diag tools
  yum: state=present pkg={{ item }}
  sudo: yes
  with_items:
    - nss-mdns
    - avahi-tools

- name: Configure common LAN filesystem mounts comment
  lineinfile: state="present" dest="/etc/fstab" regexp="^# HTPC" line="# HTPC Mounts"

- name: Configure common LAN filesystem mounts
  lineinfile: state="present" dest="/etc/fstab" insertafter="^# HTPC" regexp="^//htpc.local/Apps" line="//htpc.local/Apps /media/Apps cifs noauto,username=Craig 0 0"

