---

# LAN user accounts

- name: Create regular user accounts
  user: state="present" name="{{ item }}" createhome="yes" password="$6$w0hK n31w$RxjfrTssYs/F0Q7lwPtDVFA1cJftAVaP3MiMUxEwZqFTijEIfBqdhVdW6Gj3fAjHcnUT1yR1zTEw.EbBYhMp61"
  with_items: users_list

- name: Create super user accounts
  user: state="present" name="{{ item }}" createhome="yes" password="$6$w0hK n31w$RxjfrTssYs/F0Q7lwPtDVFA1cJftAVaP3MiMUxEwZqFTijEIfBqdhVdW6Gj3fAjHcnUT1yR1zTEw.EbBYhMp61"
  with_items: super_users_list

- name: Add warning comment to super users sudoers file
  lineinfile: state="present" dest="/etc/sudoers.d/{{ item }}" create="yes" insertbefore="BOF" regexp="^#" line="## Automatically Managed by Ansible, Manual Changes Will Be Lost!"
  with_items: super_users_list

- name: Allow super users full sudo privs
  # NB: Full line in quotes due to : char, see ansible YAML disclaimer
  lineinfile: 'state="present" dest="/etc/sudoers.d/{{ item }}" create="yes" regexp="^{{ item }}" line="{{ item }} ALL=(ALL) NOPASSWD: ALL"'
  with_items: super_users_list

