---

- name: Core Development Tools
  yum: state=present pkg={{ item }}
  with_items:
    - vim-enhanced
    - git
    - subversion
    - patchutils
    - pkgconfig
    - make
    - cmake
    - autoconf
    - automake
    - binutils
    - elfutils
    - gcc
    - gdb
    - strace
    - ltrace
    - kernel-headers
    - glibc-devel
    - wget
    - curl

- name: Download sublime text
  shell: '/usr/bin/wget "{{ sublime_url }}{{ sublime_name }}" chdir=/opt creates="/opt/{{ sublime_name }}"'
  register: downloaded_sublime
  when: install_sublime

- name: Extract sublime text
  unarchive: src="/opt/{{ sublime_name }}" dest=/opt/
  when: downloaded_sublime|changed

- name: Set current sublime link
  file: src=/opt/{{ sublime_unzipped }} dest=/opt/sublime_text
        owner=root group=root state=link
  when: install_sublime

- name: Link Sublime Text executable into /opt/bin
  file: src=/opt/sublime_text/sublime_text dest=/opt/bin/sublime_text owner=root group=root state=link
  when: install_sublime

- name: Create sublime desktop icon
  copy: 'src=sublime_text.desktop dest=/usr/share/applications/sublime_text.desktop owner=root group=root'
  when: install_sublime

- name: Download atom
  get_url: url="{{ atom_url }}" dest="/opt/{{ atom_name }}" mode=0644
  register: downloaded_atom
  when: install_atom

- name: Install atom
  yum: state=present pkg=/opt/{{ atom_name }}
  when: downloaded_atom|changed
