---

- name: Core User Tools
  yum: state=present pkg={{ item }}
  with_items:
    - keepassx
    - conky

- name: Make an /opt/bin directory
  file: state="directory" path="/opt/bin" owner="root" group="root" mode="0755"

