---

- name: Install Docker and tools
  yum: state=present pkg={{ item }}
  with_items:
    - docker-io
    - fedora-dockerfiles

- name: Install fig
  pip: state=present name=fig

- name: Add docker users to docker group
  user: name={{ item }} append=yes groups=dockerroot
  with_items: docker_users

- name: Start docker
  service: name=docker enabled=yes state=started

