---

- name: rebuild initramfs
  shell: '/usr/bin/dracut -f'

- name: reboot to multi user
  shell: '/bin/ln -sf /usr/lib/systemd/system/multi-user.target /etc/systemd/system/default.target && /usr/sbin/reboot'

- name: reboot to graphical
  shell: '/bin/ln -sf /usr/lib/systemd/system/graphical.target /etc/systemd/system/default.target && /usr/sbin/reboot'

