----

- name: Core Development Tools
  yum: pkg=$item state=latest
  with_items:
    - vim-enhanced
    - git
    - subversion
    - mercurial
    - patchutils
    - pkgconfig
    - make
    - cmake
    - autoconf
    - automake
    - binutils
    - elfutils
    - gcc
    - gdb
    - strace
    - ltrace
    - kernel-headers
    - glibc-devel
    - wget
    - curl
  tags:
    - centos_5 centos_6 fedora_19

- include: python.yml tags=pythondev
- include: kinect.yml tags=kinectdev
- include: javascript.yml tags=javascriptdev
- include: electronics.yml tags=electronicsdev

