---

- name: Configure adobe repo
  copy: src=adobe/etc/yum.repos.d/adobe.repo
        dest=/etc/yum.repos.d/adobe.repo
        owner=root group=root

- name: Install Adobe
  yum: state=present enablerepo="adobe" pkg={{ item }}
  with_items:
    - "flash-plugin"

