---

# Steam Gaming Platform & Game Tweaks / Fixes / Workarounds

- name: Configure RPM Fusion repo
  copy: src=steam/etc/yum.repos.d/rpmfusion.repo
        dest=/etc/yum.repos.d/rpmfusion.repo
        owner=root group=root

- name: Configure Fedora Steam repo
  copy: src=steam/etc/yum.repos.d/steam.repo
        dest=/etc/yum.repos.d/steam.repo
        owner=root group=root

- name: Install Steam
  yum: state=present enablerepo="rpmfusion-free,rpmfusion-free-updates,rpmfusion-nonfree,rpmfusion-nonfree-updates,steam" name="steam"

