---

- name: systemd daemon reload
  shell: '/bin/systemctl daemon-reload'

- name: systemd vnc service enable
  shell: '/bin/systemctl enable vncserver@:10.service'

- name: systemd vnc service start
  shell: '/bin/systemctl start vncserver@:10.service'

- name: systemd vnc service disable
  shell: '/bin/systemctl disable vncserver@:10.service'

- name: systemd vnc service stop
  shell: '/bin/systemctl stop vncserver@:10.service'

